/* REALIZAR UN COMPONENTE QUE PERMITA MOSTRAR TODAS LAS MASCOTAS DISPONIBLES
PARA ADOPCIÓN POR PARTE DE USUARIOS REGISTRADOS A USUARIOS NOO REGISTRADOS, ESTOS
PODRÁN ENVIAR UN FORMULARIO EN EL QUE PODRÁ APLICAR COMO ADOPTANTE DE UNA MASCOTA.
eL CENTRO DE ADOPCIÓN SE PONDRÁ EN CONTACTO CON ESTA PERSONA POR MEDIO EXTERNOS A PETHOME. */